services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: fastapi-prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
